/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.computerPart;

import com.example.computerPart.ui.MainWindow;
import javax.swing.*;
//import java.awt.*;

public class App {
    public static void main(String[] args) {
        try {
            // Set system look and feel
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        SwingUtilities.invokeLater(() -> {
            MainWindow window = new MainWindow();
            window.setVisible(true);
        });
    }
}
